// <auto-generated />
namespace GR.LFAForum.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Databaseko : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Databaseko));
        
        string IMigrationMetadata.Id
        {
            get { return "201608281453504_Databaseko"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
